import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const PROJECT_URL='https://xnoalyxxrjyovivdeojo.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_oakIu8ywKQLibfDJUDYIVg_XsNNZi66';
const supabase=createClient(PROJECT_URL,PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const API=`${PROJECT_URL}/functions/v1/admin-api`;
const BOOTSTRAP=`${PROJECT_URL}/functions/v1/admin-bootstrap`;
let LANG=localStorage.getItem('dc_admin_lang')||'ar';
let VIEW='overview';
let session=null;
let refreshTimer=null;

const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const tr=(ar,en)=>LANG==='ar'?ar:en;
const fmt=n=>new Intl.NumberFormat(LANG==='ar'?'ar-IQ':'en-US').format(Number(n||0));
const fmtDate=v=>v?new Intl.DateTimeFormat(LANG==='ar'?'ar-IQ':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const statusClass=s=>['SUCCEEDED','PUBLISHED','COMPLETED','SENT'].includes(s)?'good':['FAILED','BLOCKED'].includes(s)?'bad':['QUEUED','RUNNING','DRAFT','PENDING'].includes(s)?'warn':'';

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function setLoading(v){$('#content')?.classList.toggle('loading',v)}
function applyLanguage(){document.documentElement.lang=LANG;document.documentElement.dir=LANG==='ar'?'rtl':'ltr';document.body.dir=document.documentElement.dir;$$('.language button').forEach(b=>b.classList.toggle('active',b.dataset.lang===LANG));$('#authIntro').textContent=tr('لوحة واحدة لاكتشاف الفرص، تدقيقها، بناء النماذج، ومتابعة التواصل.','One operating surface for discovery, audits, prototypes and outreach.');renderNav();if(session)renderView()}
function renderNav(){const labels={overview:['نظرة عامة','Overview'],leads:['الفرص والعملاء','Leads & opportunities'],prototypes:['النماذج','Prototypes'],outreach:['التواصل','Outreach'],automation:['الأتمتة','Automation']};$$('.navItem').forEach(b=>{b.querySelector('span').textContent=labels[b.dataset.view][LANG==='ar'?0:1]});$('#viewTitle').textContent=labels[VIEW][LANG==='ar'?0:1]}

async function getSession(){const {data}=await supabase.auth.getSession();session=data.session;return session}
async function api(action,{method='GET',body}={}){await getSession();if(!session)throw new Error('NO_SESSION');const r=await fetch(`${API}?action=${encodeURIComponent(action)}`,{method,headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(r.status===401||r.status===403){await supabase.auth.signOut();showAuth();throw new Error('FORBIDDEN')}if(!r.ok){const e=new Error(data.error||`HTTP_${r.status}`);e.data=data;throw e}return data}

function showAuth(){clearInterval(refreshTimer);session=null;$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}
function showApp(){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');renderNav();renderView();clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(VIEW==='overview'||VIEW==='automation')renderView(false)},30000)}

$('#loginTab').onclick=()=>{setAuthTab('login')};$('#setupTab').onclick=()=>{setAuthTab('setup')};
function setAuthTab(which){$('#loginTab').classList.toggle('active',which==='login');$('#setupTab').classList.toggle('active',which==='setup');$('#loginForm').classList.toggle('active',which==='login');$('#setupForm').classList.toggle('active',which==='setup');$('#authMessage').textContent=''}

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');btn.disabled=true;$('#authMessage').textContent='';try{const {data,error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)throw error;session=data.session;showApp()}catch(err){$('#authMessage').textContent=tr('تعذر تسجيل الدخول. تحقق من البيانات.','Sign in failed. Check your credentials.')}finally{btn.disabled=false}});

$('#setupForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');btn.disabled=true;$('#authMessage').textContent='';try{const email=$('#setupEmail').value.trim(),password=$('#setupPassword').value;const r=await fetch(BOOTSTRAP,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({setup_code:$('#setupCode').value.trim(),email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error||'SETUP_FAILED');const sign=await supabase.auth.signInWithPassword({email,password});if(sign.error)throw sign.error;session=sign.data.session;toast(tr('تم إنشاء حساب المالك','Owner account created'));showApp()}catch(err){const map={already_initialized:tr('تم إعداد النظام مسبقًا. استخدم تسجيل الدخول.','System is already initialized. Use sign in.'),invalid_or_expired_setup_code:tr('رمز الإعداد غير صحيح أو منتهي.','Setup code is invalid or expired.'),invalid_input:tr('تحقق من البريد وكلمة المرور (12 حرفًا على الأقل).','Check email and password (minimum 12 characters).')};$('#authMessage').textContent=map[err.message]||tr('تعذر إكمال الإعداد.','Setup could not be completed.')}finally{btn.disabled=false}});

$$('.language button').forEach(b=>b.onclick=()=>{LANG=b.dataset.lang;localStorage.setItem('dc_admin_lang',LANG);applyLanguage()});
$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();showAuth()};
$('#refreshBtn').onclick=()=>renderView();
$('#nav').addEventListener('click',e=>{const b=e.target.closest('.navItem');if(!b)return;VIEW=b.dataset.view;$$('.navItem').forEach(x=>x.classList.toggle('active',x===b));renderNav();renderView()});

async function renderView(showLoader=true){if(!session)return;if(showLoader)setLoading(true);try{if(VIEW==='overview')await renderOverview();else if(VIEW==='leads')await renderLeads();else if(VIEW==='prototypes')await renderPrototypes();else if(VIEW==='outreach')await renderOutreach();else await renderAutomation()}catch(e){$('#content').innerHTML=`<div class="empty">${esc(tr('تعذر تحميل البيانات.','Could not load data.'))}</div>`}finally{setLoading(false)}}

async function renderOverview(){const d=await api('summary'),m=d.metrics||{};$('#content').innerHTML=`<div class="heroStrip"><div class="heroPanel"><span class="eyebrow">DIGITAL COMPASS / LIVE OPERATIONS</span><h2>${tr('من الاكتشاف إلى التواصل، من مكان واحد.','From discovery to outreach, one operating surface.')}</h2><p>${tr('راقب مسار العملاء، شغّل المراحل يدويًا عند الحاجة، واترك الأتمتة اليومية تعمل في الخلفية.','Monitor the lead pipeline, trigger any stage when needed, and keep the daily automation running underneath.')}</p></div><div class="commandPanel"><h3>${tr('تشغيل المحرك','Run the engine')}</h3><p>${tr('الأمر الكامل ينفذ: Discovery → Shortlist → Audit → Qualification → Brand Prep → Prototypes → Outreach Drafts.','Full pipeline runs Discovery → Shortlist → Audit → Qualification → Brand Prep → Prototypes → Outreach Drafts.')}</p><button class="runFull" data-command="FULL_PIPELINE">${tr('تشغيل العملية كاملة','Run full pipeline')}</button><div class="stageGrid">${stageButtons()}</div></div></div>${metricsHtml(m)}${commandsTable(d.recent_commands||[],tr('آخر عمليات التشغيل','Recent runs'))}`;bindCommands()}
function metricsHtml(m){const items=[['companies',tr('الشركات المكتشفة','Discovered companies')],['candidates',tr('مرشحون','Candidates')],['shortlists',tr('قوائم مختصرة','Shortlisted')],['audits',tr('تدقيق مكتمل','Audits completed')],['opportunities',tr('فرص مؤهلة','Qualified opportunities')],['prototypes',tr('نماذج منشورة','Published prototypes')],['drafts',tr('رسائل جاهزة','Outreach drafts')],['approved',tr('موافق عليها للإرسال','Approved to send')]];return `<div class="metrics">${items.map(([k,l])=>`<div class="metric"><span class="label">${l}</span><strong>${fmt(m[k])}</strong><div class="mini">LIVE DATABASE</div></div>`).join('')}</div>`}
function stageButtons(){const s=[['DISCOVERY',tr('اكتشاف','Discovery')],['SHORTLIST',tr('اختيار يومي','Shortlist')],['AUDIT',tr('تدقيق','Audit')],['QUALIFY',tr('تأهيل','Qualify')],['BRAND_PREP',tr('تحليل الهوية','Brand prep')],['PROTOTYPES',tr('النماذج','Prototypes')],['OUTREACH_DRAFTS',tr('مسودات التواصل','Outreach drafts')]];return s.map(([v,l])=>`<button class="stageBtn" data-command="${v}">${l}</button>`).join('')}
function bindCommands(){$$('[data-command]').forEach(b=>b.onclick=async()=>{const type=b.dataset.command;if(type==='FULL_PIPELINE'&&!confirm(tr('تشغيل العملية الكاملة الآن؟ سيتم تنفيذ كل المراحل بالتتابع.','Run the full pipeline now? Every stage will execute sequentially.')))return;b.disabled=true;try{await api('command',{method:'POST',body:{command_type:type}});toast(tr('تمت إضافة الأمر إلى قائمة التنفيذ','Command queued'));await renderView(false)}catch(e){toast(e.message==='already_pending'?tr('هذا الأمر موجود أصلًا في قائمة التنفيذ','This command is already queued'):tr('تعذر إضافة الأمر','Could not queue command'))}finally{b.disabled=false}})}

async function renderLeads(){const d=await api('leads');const items=d.items||[];$('#content').innerHTML=`<div class="section"><div class="sectionHead"><h3>${tr('الفرص والعملاء','Leads & opportunities')}</h3><span>${fmt(items.length)}</span></div><div class="tableWrap"><table class="table"><thead><tr><th>${tr('الشركة','Company')}</th><th>${tr('السوق','Market')}</th><th>${tr('القطاع','Sector')}</th><th>${tr('المسار','Track')}</th><th>${tr('الدرجة','Score')}</th><th>${tr('الخطوة التالية','Next step')}</th></tr></thead><tbody>${items.map(x=>{const c=x.companies||{};return `<tr><td><strong>${esc(c.name||'—')}</strong><br><span>${esc(c.city||'')}</span></td><td>${esc(c.country||x.country||'—')}</td><td>${esc(c.sector||'—')}</td><td><span class="pill">${esc(x.opportunity_track||'—')}</span></td><td><span class="score">${fmt(x.pre_audit_score)}</span></td><td>${esc(x.recommended_next_step||'—')}</td></tr>`}).join('')}</tbody></table></div></div>`}

async function renderPrototypes(){const d=await api('prototypes'),items=d.items||[];$('#content').innerHTML=`<div class="section"><div class="sectionHead"><h3>${tr('النماذج المنشورة','Published prototypes')}</h3><span>${fmt(items.length)}</span></div><div class="tableWrap"><table class="table"><thead><tr><th>${tr('الشركة','Company')}</th><th>${tr('المستوى','Level')}</th><th>${tr('الحالة','Status')}</th><th>${tr('الإصدار','Version')}</th><th>${tr('الهوية','Brand gate')}</th><th>${tr('الرابط','Link')}</th></tr></thead><tbody>${items.map(x=>`<tr><td><strong>${esc(x.companies?.name||'—')}</strong><br>${esc(x.companies?.sector||'')}</td><td>${esc(x.prototype_level)}</td><td><span class="pill ${statusClass(x.generation_status)}">${esc(x.generation_status)}</span></td><td>V${fmt(x.version)}</td><td>${esc(x.brand_gate_status||'—')}</td><td>${x.public_url?`<a class="link" href="${esc(x.public_url)}" target="_blank" rel="noopener">${tr('فتح','Open')} ↗</a>`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`}

async function renderOutreach(){const d=await api('outreach'),items=d.items||[];$('#content').innerHTML=`<div class="section"><div class="sectionHead"><h3>${tr('التواصل والموافقات','Outreach & approvals')}</h3><span>${fmt(items.length)}</span></div><div class="tableWrap"><table class="table"><thead><tr><th>${tr('الشركة','Company')}</th><th>${tr('المستلم','Recipient')}</th><th>${tr('الموضوع','Subject')}</th><th>${tr('الحالة','Status')}</th><th>${tr('النموذج','Preview')}</th><th>${tr('موافقة الإرسال','Send approval')}</th></tr></thead><tbody>${items.map(x=>`<tr><td><strong>${esc(x.companies?.name||'—')}</strong><br>${esc(x.language||'')}</td><td>${esc(x.recipient_address||'—')}</td><td>${esc(x.subject||'—')}</td><td><span class="pill ${statusClass(x.status)}">${esc(x.status)}</span></td><td>${x.preview_url?`<a class="link" href="${esc(x.preview_url)}" target="_blank" rel="noopener">${tr('معاينة','Preview')} ↗</a>`:'—'}</td><td><button class="approveBtn ${x.approved_for_send?'on':''}" data-approve="${x.id}" data-value="${x.approved_for_send?'0':'1'}">${x.approved_for_send?tr('موافق ✓','Approved ✓'):tr('اعتماد','Approve')}</button></td></tr>`).join('')}</tbody></table></div></div>`;$$('[data-approve]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('approve_outreach',{method:'POST',body:{id:Number(b.dataset.approve),approved:b.dataset.value==='1'}});toast(tr('تم تحديث الموافقة','Approval updated'));await renderOutreach()}catch{toast(tr('تعذر تحديث الموافقة','Could not update approval'))}})}

async function renderAutomation(){const d=await api('commands'),items=d.items||[];$('#content').innerHTML=`<div class="commandPanel"><h3>${tr('التحكم اليدوي','Manual controls')}</h3><p>${tr('الأتمتة اليومية تبقى فعالة. هذه الأزرار تسمح بإعادة تشغيل مرحلة أو العملية كاملة عند الحاجة.','Daily automation stays active. These controls let you rerun a stage or the full pipeline when needed.')}</p><button class="runFull" data-command="FULL_PIPELINE">${tr('تشغيل العملية كاملة','Run full pipeline')}</button><div class="stageGrid">${stageButtons()}</div></div>${commandsTable(items,tr('سجل الأوامر','Command history'))}`;bindCommands();$$('[data-cancel]').forEach(b=>b.onclick=async()=>{try{await api('cancel_command',{method:'POST',body:{id:Number(b.dataset.cancel)}});toast(tr('تم إلغاء الأمر','Command cancelled'));renderAutomation()}catch{toast(tr('تعذر إلغاء الأمر','Could not cancel command'))}})}
function commandsTable(items,title){return `<div class="section"><div class="sectionHead"><h3>${title}</h3><span>${fmt(items.length)}</span></div><div class="tableWrap"><table class="table"><thead><tr><th>ID</th><th>${tr('الأمر','Command')}</th><th>${tr('الحالة','Status')}</th><th>${tr('الطلب','Requested')}</th><th>${tr('الانتهاء','Completed')}</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td>#${x.id}</td><td><strong>${esc(x.command_type)}</strong></td><td><span class="pill ${statusClass(x.status)}">${esc(x.status)}</span></td><td>${fmtDate(x.requested_at)}</td><td>${fmtDate(x.completed_at)}</td><td>${x.status==='QUEUED'?`<button class="approveBtn" data-cancel="${x.id}">${tr('إلغاء','Cancel')}</button>`:''}</td></tr>`).join('')}</tbody></table></div></div>`}

(async function boot(){applyLanguage();const s=await getSession();if(s)showApp();else showAuth()})();
