import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const PROJECT_URL='https://xnoalyxxrjyovivdeojo.supabase.co';
const KEY='sb_publishable_oakIu8ywKQLibfDJUDYIVg_XsNNZi66';
const API=`${PROJECT_URL}/functions/v1/admin-user-api`;
const supabase=createClient(PROJECT_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let profile=null;
const has=p=>profile&&(profile.role==='OWNER'||(profile.permissions||[]).includes('*')||(profile.permissions||[]).includes(p));
const mapNode=n=>{if(n.dataset?.view==='leads')return'leads.view';if(n.dataset?.view==='prototypes')return'prototypes.view';if(n.dataset?.view==='outreach')return'outreach.view';if(n.dataset?.view==='automation')return'automation.view';if(n.dataset?.view==='settings')return'settings.view';const h=n.getAttribute?.('href')||'';if(h.includes('users.html'))return'users.manage';if(h.includes('social-management.html'))return'social_management.view';if(h.includes('social.html'))return'social.view';if(h.includes('view=leads'))return'leads.view';if(h.includes('view=prototypes'))return'prototypes.view';if(h.includes('view=outreach'))return'outreach.view';if(h.includes('view=automation'))return'automation.view';if(h.includes('view=settings'))return'settings.view';return null};
function applyNav(){document.querySelectorAll('.navItem').forEach(n=>{const p=mapNode(n);if(p)n.style.display=has(p)?'':'none'})}
function applyActions(){if(!has('automation.run'))document.querySelectorAll('[data-stage],[data-command],[data-cancel]').forEach(x=>x.style.display='none');if(!has('social.manage')){['#discoverAdvertisersBtn','#manualSocialForm','#saveSocialSettings'].forEach(s=>document.querySelectorAll(s).forEach(x=>x.style.display='none'))}if(!has('settings.manage'))document.querySelectorAll('.saveSetting,[data-save-setting]').forEach(x=>x.style.display='none');if(!has('outreach.manage'))document.querySelectorAll('[data-approve],[data-edit-outreach],[data-save-outreach]').forEach(x=>x.style.display='none');if(!has('social_management.manage')&&location.pathname.endsWith('/social-management.html')){document.querySelectorAll('#panel button:not([data-tab]), .topActions button:not(#refreshBtn)').forEach(x=>x.style.display='none')}}
async function boot(){const {data}=await supabase.auth.getSession();if(!data.session)return;const u=new URL(API);u.searchParams.set('action','current');const r=await fetch(u,{headers:{apikey:KEY,Authorization:`Bearer ${data.session.access_token}`}});if(!r.ok)return;const d=await r.json();profile=d.user;window.DC_ACCESS_PROFILE=profile;applyNav();applyActions();new MutationObserver(()=>{applyNav();applyActions()}).observe(document.body,{subtree:true,childList:true})}
boot().catch(()=>{});