import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const PROJECT_URL='https://xnoalyxxrjyovivdeojo.supabase.co';
const KEY='sb_publishable_oakIu8ywKQLibfDJUDYIVg_XsNNZi66';
const API=`${PROJECT_URL}/functions/v1/admin-user-api`;
const supabase=createClient(PROJECT_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let profile=null;
const has=p=>profile&&(profile.role==='OWNER'||(profile.permissions||[]).includes('*')||(profile.permissions||[]).includes(p));
const mapNode=n=>{if(n.dataset?.view==='overview')return'dashboard.view';if(n.dataset?.view==='leads')return'leads.view';if(n.dataset?.view==='prototypes')return'prototypes.view';if(n.dataset?.view==='outreach')return'outreach.view';if(n.dataset?.view==='automation')return'automation.view';if(n.dataset?.view==='settings')return'settings.view';const h=n.getAttribute?.('href')||'';if(h==='./'||h.endsWith('/admin/'))return'dashboard.view';if(h.includes('users.html'))return'users.manage';if(h.includes('social-management.html'))return'social_management.view';if(h.includes('social.html'))return'social.view';if(h.includes('view=leads'))return'leads.view';if(h.includes('view=prototypes'))return'prototypes.view';if(h.includes('view=outreach'))return'outreach.view';if(h.includes('view=automation'))return'automation.view';if(h.includes('view=settings'))return'settings.view';return null};
function applyNav(){document.querySelectorAll('.navItem').forEach(n=>{const p=mapNode(n);if(p)n.style.display=has(p)?'':'none'})}
function firstAllowed(){if(has('dashboard.view'))return'./';if(has('leads.view'))return'./?view=leads';if(has('social.view'))return'./social.html';if(has('social_management.view'))return'./social-management.html';if(has('prototypes.view'))return'./?view=prototypes';if(has('outreach.view'))return'./?view=outreach';if(has('automation.view'))return'./?view=automation';if(has('settings.view'))return'./?view=settings';if(has('users.manage'))return'./users.html';return'./access.html'}
function enforceRoute(){const p=location.pathname,q=new URLSearchParams(location.search),view=q.get('view')||'overview';let required=null;if(p.endsWith('/users.html'))required='users.manage';else if(p.endsWith('/social-management.html'))required='social_management.view';else if(p.endsWith('/social.html'))required='social.view';else if(p.endsWith('/admin/')||p.endsWith('/admin/index.html'))required={overview:'dashboard.view',leads:'leads.view',prototypes:'prototypes.view',outreach:'outreach.view',automation:'automation.view',settings:'settings.view'}[view]||'dashboard.view';if(required&&!has(required)){const dest=firstAllowed(),now=`.${location.pathname.split('/admin')[1]||'/'}`+(location.search||'');if(dest!==now)location.replace(dest)}}
function applyActions(){if(!has('automation.run'))document.querySelectorAll('[data-stage],[data-command],[data-cancel]').forEach(x=>x.style.display='none');if(!has('social.manage')){['#discoverAdvertisersBtn','#manualSocialForm','#saveSocialSettings'].forEach(s=>document.querySelectorAll(s).forEach(x=>x.style.display='none'))}if(!has('settings.manage'))document.querySelectorAll('.saveSetting,[data-save-setting]').forEach(x=>x.style.display='none');if(!has('outreach.manage'))document.querySelectorAll('[data-approve],[data-edit-outreach],[data-save-outreach]').forEach(x=>x.style.display='none');if(!has('social_management.manage')&&location.pathname.endsWith('/social-management.html')){document.querySelectorAll('#panel button:not([data-tab]), .topActions button:not(#refreshBtn)').forEach(x=>x.style.display='none')}}
async function boot(){const {data}=await supabase.auth.getSession();if(!data.session)return;const u=new URL(API);u.searchParams.set('action','current');const r=await fetch(u,{headers:{apikey:KEY,Authorization:`Bearer ${data.session.access_token}`}});if(!r.ok)return;const d=await r.json();profile=d.user;window.DC_ACCESS_PROFILE=profile;enforceRoute();applyNav();applyActions();new MutationObserver(()=>{applyNav();applyActions()}).observe(document.body,{subtree:true,childList:true})}
boot().catch(()=>{});