import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const PROJECT_URL='https://xnoalyxxrjyovivdeojo.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_oakIu8ywKQLibfDJUDYIVg_XsNNZi66';
const supabase=createClient(PROJECT_URL,PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const API=`${PROJECT_URL}/functions/v1/admin-api`;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=n=>new Intl.NumberFormat('ar-IQ').format(Number(n||0));
let session=null;

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function scoreClass(v){const n=Number(v);return n>=75?'scoreGood':n>=50?'scoreWarn':'scoreBad'}
function score(v){if(v===null||v===undefined)return '<span class="pill">—</span>';const n=Math.max(0,Math.min(100,Number(v)||0));return `<span class="scoreGauge ${scoreClass(n)}"><strong>${fmt(n)}</strong><span class="scoreBar"><i style="width:${n}%"></i></span></span>`}
function statusClass(s){return ['COMPLETED','QUALIFIED','ACTIVE'].includes(s)?'good':['FAILED','BLOCKED'].includes(s)?'bad':['PENDING','RUNNING','NEEDS_REVIEW','REVIEW'].includes(s)?'warn':''}

async function getSession(){const {data}=await supabase.auth.getSession();session=data.session;return session}
async function api(action,{method='GET',body,params={}}={}){await getSession();if(!session)throw new Error('NO_SESSION');const url=new URL(API);url.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,String(v)));const r=await fetch(url,{method,headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(r.status===401||r.status===403){location.href='./';throw new Error('FORBIDDEN')}if(!r.ok){const e=new Error(data.error||`HTTP_${r.status}`);e.data=data;throw e}return data}

async function boot(){if(!(await getSession())){location.href='./';return}$('#socialApp').classList.remove('hidden');await loadAll()}
async function loadAll(){try{const [d,s]=await Promise.all([api('social'),api('settings')]);renderMetrics(d.metrics||{});renderRows(d.items||[]);renderSettings((s.items||[]).find(x=>x.setting_key==='iraq_social_engine')?.setting_value||{});}catch(e){console.error(e);toast('تعذر تحميل Social Engine')}}
function renderMetrics(m){const items=[['profiles','حسابات مرتبطة'],['pending','Audit Pending'],['completed','Audit مكتمل'],['review','Needs Review'],['opportunities','فرص إدارة'],['active_workspaces','عملاء إدارة نشطون'],['published_content','محتوى منشور'],['pending_inbox','Inbox بحاجة متابعة']];$('#metrics').innerHTML=items.map(([k,l])=>`<div class="metric"><span class="label">${l}</span><strong>${fmt(m[k])}</strong><div class="mini">IRAQ SOCIAL</div></div>`).join('')}
function renderRows(items){$('#rowCount').textContent=fmt(items.length);$('#socialRows').innerHTML=items.map(x=>`<tr class="socialRow" data-company="${x.company_id}"><td><strong>${esc(x.name||'—')}</strong><br><span>${esc(x.city||'')} · ${esc(x.sector||'')}</span></td><td><a class="socialProfileLink" href="${esc(x.profile_url||'#')}" target="_blank" rel="noopener nofollow">${esc(x.platform||'—')} ↗</a></td><td><span class="pill ${statusClass(x.audit_status)}">${esc(x.audit_status||'NOT_AUDITED')}</span></td><td>${score(x.overall_social_health_score)}</td><td>${score(x.management_need_score)}</td><td>${x.has_public_ad_activity?'<span class="pill good">PUBLIC ADS</span>':'<span class="pill">—</span>'}</td><td>${esc(x.recommended_next_action||'AUDIT_REQUIRED')}</td></tr>`).join('')||`<tr><td colspan="7">لا توجد نتائج بعد.</td></tr>`;$$('[data-company]').forEach(r=>r.onclick=e=>{if(e.target.closest('a'))return;openCompany(Number(r.dataset.company))})}

async function openCompany(id){const d=$('#drawer'),box=$('#drawerContent');d.classList.remove('hidden');d.setAttribute('aria-hidden','false');box.innerHTML='<div class="empty">تحميل…</div>';try{const x=await api('social_detail',{params:{id}}),c=x.company||{},latest=(x.audits||[])[0]||{};box.innerHTML=`<span class="eyebrow">IRAQ SOCIAL / ${esc(c.city||'')}</span><h2 class="drawerTitle">${esc(c.name||'—')}</h2><div class="drawerMeta">${esc(c.sector||'—')}</div><div class="detailScores"><div class="detailScore"><span>Social Health</span><b>${latest.overall_social_health_score??'—'}</b></div><div class="detailScore"><span>Management Need</span><b>${latest.management_need_score??'—'}</b></div><div class="detailScore"><span>Posting Consistency</span><b>${latest.posting_consistency_score??'—'}</b></div><div class="detailScore"><span>Content Quality</span><b>${latest.content_quality_score??'—'}</b></div><div class="detailScore"><span>Brand Consistency</span><b>${latest.brand_consistency_score??'—'}</b></div><div class="detailScore"><span>Conversion Path</span><b>${latest.conversion_path_score??'—'}</b></div></div>${section('الحسابات',(x.profiles||[]).map(p=>`<div class="miniRow"><b>${esc(p.platform)}</b><p><a class="link" href="${esc(p.profile_url)}" target="_blank" rel="noopener">${esc(p.handle||p.profile_url)} ↗</a></p></div>`).join(''))}${section('أدلة الـAudit',evidence(latest.evidence))}${section('الفجوات',jsonList(latest.gaps))}${section('الإجراءات المقترحة',jsonList(latest.recommended_actions))}${section('الإعلانات العامة',(x.public_ads||[]).map(a=>`<div class="adCard"><b>${esc(a.platform)} · ${esc(a.creative_type||'Ad')}</b><p>${esc(a.creative_text||a.call_to_action||'Public ad observed')}</p>${a.ad_url?`<a class="link" href="${esc(a.ad_url)}" target="_blank" rel="noopener">فتح الإعلان ↗</a>`:''}</div>`).join(''))}${section('فرص الإدارة',(x.opportunities||[]).map(o=>`<div class="miniRow"><b>${esc(o.priority)} · ${fmt(o.management_need_score)}</b><p>${esc(o.problem_summary||'')}</p><p>${esc(o.recommended_next_action||'')}</p></div>`).join(''))}`;}catch(e){console.error(e);box.innerHTML='<div class="empty">تعذر تحميل التفاصيل.</div>'}}
function section(title,body){return `<div class="drawerSection"><h3>${title}</h3><div class="miniList">${body||'<div class="miniRow"><p>لا توجد بيانات بعد.</p></div>'}</div></div>`}
function evidence(v){const arr=Array.isArray(v)?v:[];return `<div class="evidenceList">${arr.map(x=>`<div>${esc(typeof x==='string'?x:(x.summary||x.type||JSON.stringify(x)))}</div>`).join('')}</div>`}
function jsonList(v){const arr=Array.isArray(v)?v:[];return arr.map(x=>`<div class="miniRow"><p>${esc(typeof x==='string'?x:JSON.stringify(x))}</p></div>`).join('')}
function closeDrawer(){$('#drawer').classList.add('hidden');$('#drawer').setAttribute('aria-hidden','true')}

document.addEventListener('click',e=>{if(e.target.closest('[data-close-drawer]'))closeDrawer()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});
$('#refreshBtn').onclick=loadAll;
$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.href='./'};
$$('[data-command]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('command',{method:'POST',body:{command_type:b.dataset.command}});toast('تمت إضافة الأمر إلى قائمة التنفيذ')}catch(e){toast(e.message==='already_pending'?'الأمر موجود أصلًا في قائمة التنفيذ':'تعذر إضافة الأمر')}finally{b.disabled=false}});

function renderSettings(v){$('#settingsBox').innerHTML=`<div class="socialSettings"><label>عدد الحسابات يوميًا<input id="dailyTarget" type="number" min="1" max="100" value="${esc(v.daily_audit_target??25)}"></label><label>Minimum Need Score<input id="minNeed" type="number" min="0" max="100" value="${esc(v.minimum_management_need_score??65)}"></label><label>Hot Score<input id="hotScore" type="number" min="0" max="100" value="${esc(v.hot_score??80)}"></label><label>Very Hot Score<input id="veryHotScore" type="number" min="0" max="100" value="${esc(v.very_hot_score??90)}"></label><label class="socialToggle"><span>Public Ad Monitoring</span><input id="publicAds" type="checkbox" ${v.public_ad_monitoring!==false?'checked':''}></label><label class="socialToggle"><span>Authorized Ad Metrics</span><input id="authAds" type="checkbox" ${v.authorized_ad_metrics!==false?'checked':''}></label><label class="socialToggle"><span>Client approval before publishing</span><input id="clientApproval" type="checkbox" ${v.client_approval_required_for_publishing!==false?'checked':''}></label><label class="socialToggle"><span>Auto-send outreach</span><input id="autoSend" type="checkbox" ${v.auto_send_outreach?'checked':''}></label></div><button id="saveSocialSettings" class="saveSocial">حفظ إعدادات Social Iraq</button>`;$('#saveSocialSettings').onclick=saveSettings}
async function saveSettings(){const value={enabled:true,country:'Iraq',platforms:['INSTAGRAM','FACEBOOK','TIKTOK'],daily_audit_target:+$('#dailyTarget').value,minimum_management_need_score:+$('#minNeed').value,hot_score:+$('#hotScore').value,very_hot_score:+$('#veryHotScore').value,public_ad_monitoring:$('#publicAds').checked,authorized_ad_metrics:$('#authAds').checked,auto_send_outreach:$('#autoSend').checked,client_approval_required_for_publishing:$('#clientApproval').checked};try{await api('update_setting',{method:'POST',body:{setting_key:'iraq_social_engine',setting_value:value}});toast('تم حفظ إعدادات Social Iraq')}catch{toast('تعذر حفظ الإعدادات')}}

boot();
