import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const PROJECT_URL='https://xnoalyxxrjyovivdeojo.supabase.co';
const KEY='sb_publishable_oakIu8ywKQLibfDJUDYIVg_XsNNZi66';
const API=`${PROJECT_URL}/functions/v1/admin-user-api`;
const supabase=createClient(PROJECT_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let session=null,current=null,items=[];
const PERMS=[
 ['dashboard.view','نظرة عامة','مشاهدة لوحة الملخص'],
 ['leads.view','الفرص — مشاهدة','فتح العملاء والفرص والتفاصيل'],['leads.manage','الفرص — تعديل','تعديل العرض والسعر والخطوات'],
 ['social.view','Social Iraq — مشاهدة','مشاهدة الاكتشاف والتدقيق'],['social.manage','Social Iraq — إدارة','تشغيل الاكتشاف وإضافة حسابات وتشغيل العمليات'],
 ['social_management.view','حسابات العملاء — مشاهدة','فتح Workspaces وبيانات العملاء'],['social_management.manage','حسابات العملاء — إدارة','الردود والمحتوى والحملات والسياسات'],
 ['prototypes.view','النماذج','مشاهدة البروتوتايبات'],
 ['outreach.view','التواصل — مشاهدة','مشاهدة الرسائل والقنوات'],['outreach.manage','التواصل — إدارة','تعديل واعتماد الرسائل'],
 ['automation.view','الأتمتة — مشاهدة','مشاهدة سجل التشغيل'],['automation.run','الأتمتة — تشغيل','تشغيل وإلغاء مراحل المحرك'],
 ['settings.view','الإعدادات — مشاهدة','مشاهدة إعدادات النظام'],['settings.manage','الإعدادات — تعديل','تغيير إعدادات التشغيل'],
 ['users.manage','المستخدمون والصلاحيات','إضافة المستخدمين وتعديل صلاحياتهم']
];
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
async function getSession(){const {data}=await supabase.auth.getSession();session=data.session;return session}
async function api(action,{method='GET',body}={}){if(!session&&!(await getSession()))throw new Error('NO_SESSION');const u=new URL(API);u.searchParams.set('action',action);const r=await fetch(u,{method,headers:{apikey:KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(r.status===401||r.status===403){if(d.error!=='permission_denied'){await supabase.auth.signOut();location.href='./access.html';}throw new Error(d.error||'forbidden')}if(!r.ok)throw new Error(d.error||`HTTP_${r.status}`);return d}
function has(p){return current?.role==='OWNER'||(current?.permissions||[]).includes('*')||(current?.permissions||[]).includes(p)}
async function boot(){if(!(await getSession())){location.href='./access.html';return}const me=await api('current');current=me.user;if(!has('users.manage')){location.href='./';return}$('#app').classList.remove('hidden');$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.href='./access.html'};$('#refreshBtn').onclick=load;$('#newUserBtn').onclick=()=>openCreate();document.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});await load()}
async function load(){try{const d=await api('list');items=d.items||[];render()}catch(e){console.error(e);toast('تعذر تحميل المستخدمين')}}
function render(){const active=items.filter(x=>x.is_active).length,admins=items.filter(x=>['OWNER','ADMIN'].includes(x.role)).length;$('#usersCount').textContent=items.length;$('#activeCount').textContent=active;$('#adminsCount').textContent=admins;$('#tableCount').textContent=items.length;$('#usersGrid').innerHTML=items.map(userCard).join('')||'<div class="empty">لا يوجد مستخدمون.</div>';$$('[data-user]').forEach(x=>x.onclick=()=>openEdit(x.dataset.user))}
function roleLabel(r){return r==='OWNER'?'OWNER':r==='ADMIN'?'ADMIN':'USER'}
function initials(x){const s=(x.display_name||x.username||'U').trim();return esc((s[0]||'U').toUpperCase())}
function userCard(x){const p=x.role==='OWNER'?['صلاحية كاملة']:(x.permissions||[]).slice(0,4);return `<button class="userCard" data-user="${esc(x.user_id)}"><div class="userHead"><div class="avatar">${initials(x)}</div><div class="userIdentity"><strong>${esc(x.display_name||x.username||'—')}</strong><span>@${esc(x.username||'—')}</span></div><span class="roleBadge ${x.role==='OWNER'?'owner':x.role==='ADMIN'?'admin':''}">${roleLabel(x.role)}</span></div><div class="userMeta"><div><small>الحالة</small><span class="stateBadge ${x.is_active?'on':'off'}">${x.is_active?'نشط':'موقوف'}</span></div><div><small>آخر دخول</small><span>${x.last_login_at?new Date(x.last_login_at).toLocaleString('ar-IQ'):'—'}</span></div></div><div class="permissionPreview">${p.map(z=>`<i>${esc(z)}</i>`).join('')}${x.role!=='OWNER'&&(x.permissions||[]).length>4?`<i>+${(x.permissions||[]).length-4}</i>`:''}</div></button>`}
function permHtml(selected=[]){const set=new Set(selected);return `<div class="permissionsBox"><h4>الصلاحيات</h4><div class="permissionGrid">${PERMS.map(([k,t,d])=>`<label class="permItem"><input type="checkbox" data-perm="${k}" ${set.has(k)||set.has('*')?'checked':''}><span><b>${t}</b><span>${d}</span></span></label>`).join('')}</div></div>`}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')}
function selectedPerms(){return $$('[data-perm]:checked').map(x=>x.dataset.perm)}
function openCreate(){openModal(`<h2 class="modalTitle">إضافة مستخدم جديد</h2><p class="modalLead">المستخدم يدخل باسم مستخدم وكلمة مرور، وبعدها تنطبق عليه الصلاحيات اللي تحددها هون.</p><div class="userForm"><label>الاسم الظاهر<input id="fName" placeholder="مثال: موظف المبيعات"></label><label>الدور<select id="fRole"><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select></label><label>اسم المستخدم<input id="fUsername" autocomplete="off" placeholder="sales1"></label><label>كلمة المرور<input id="fPassword" type="password" autocomplete="new-password" placeholder="8 أحرف على الأقل"></label>${permHtml(['dashboard.view'])}<div class="formActions"><button class="secondaryBtn" data-close>إلغاء</button><button id="createUser" class="saveUser">إنشاء المستخدم</button></div></div>`);$('#createUser').onclick=createUser}
async function createUser(){const b=$('#createUser');b.disabled=true;try{const body={display_name:$('#fName').value.trim(),username:$('#fUsername').value.trim(),password:$('#fPassword').value,role:$('#fRole').value,permissions:selectedPerms()};if(body.username.length<3)return toast('اسم المستخدم لازم يكون 3 أحرف على الأقل');if(body.password.length<8)return toast('كلمة المرور للمستخدمين الجدد لازم تكون 8 أحرف على الأقل');await api('create',{method:'POST',body});toast('تم إنشاء المستخدم');closeModal();await load()}catch(e){toast(e.message==='username_exists'?'اسم المستخدم مستخدم مسبقاً':e.message==='weak_password'?'كلمة المرور ضعيفة':'تعذر إنشاء المستخدم')}finally{b.disabled=false}}
function openEdit(id){const x=items.find(z=>z.user_id===id);if(!x)return;const owner=x.role==='OWNER';openModal(`<h2 class="modalTitle">${esc(x.display_name||x.username)}</h2><p class="modalLead">عدّل الحساب والصلاحيات. حساب OWNER محمي من التعطيل أو خفض الدور.</p><div class="userForm"><label>الاسم الظاهر<input id="eName" value="${esc(x.display_name||'')}"></label><label>الدور<select id="eRole" ${owner?'disabled':''}><option value="USER" ${x.role==='USER'?'selected':''}>USER</option><option value="ADMIN" ${x.role==='ADMIN'?'selected':''}>ADMIN</option><option value="OWNER" ${x.role==='OWNER'?'selected':''}>OWNER</option></select></label><label>اسم المستخدم<input id="eUsername" value="${esc(x.username||'')}" ${owner?'':'autocomplete="off"'}></label><label>الحالة<select id="eActive" ${owner?'disabled':''}><option value="true" ${x.is_active?'selected':''}>نشط</option><option value="false" ${!x.is_active?'selected':''}>موقوف</option></select></label>${owner?'<div class="permissionsBox"><h4>الصلاحيات</h4><div class="note">OWNER يمتلك كل الصلاحيات تلقائياً.</div></div>':permHtml(x.permissions||[])}<div class="passwordPanel"><b>تغيير كلمة المرور</b><div class="passwordRow"><input id="ePassword" type="password" autocomplete="new-password" placeholder="كلمة مرور جديدة — 8 أحرف على الأقل"><button id="changePassword">تغيير</button></div><div class="note">تغيير كلمة المرور لا يعرض الكلمة القديمة ولا يخزنها داخل جدول المستخدمين.</div></div><div class="formActions"><button class="secondaryBtn" data-close>إغلاق</button><button id="saveUser" class="saveUser">حفظ التعديلات</button></div></div>`);$('#saveUser').onclick=()=>saveUser(x);$('#changePassword').onclick=()=>changePassword(x)}
async function saveUser(x){const b=$('#saveUser');b.disabled=true;try{const body={user_id:x.user_id,display_name:$('#eName').value.trim(),username:$('#eUsername').value.trim()};if(x.role!=='OWNER'){body.role=$('#eRole').value;body.is_active=$('#eActive').value==='true';body.permissions=selectedPerms()}await api('update',{method:'POST',body});toast('تم حفظ المستخدم');closeModal();await load()}catch(e){toast(e.message==='invalid_username'?'اسم المستخدم غير صالح':e.message==='username_exists'?'اسم المستخدم مستخدم مسبقاً':'تعذر حفظ المستخدم')}finally{b.disabled=false}}
async function changePassword(x){const p=$('#ePassword').value,b=$('#changePassword');if(p.length<8)return toast('كلمة المرور الجديدة لازم تكون 8 أحرف على الأقل');b.disabled=true;try{await api('password',{method:'POST',body:{user_id:x.user_id,password:p}});$('#ePassword').value='';toast('تم تغيير كلمة المرور')}catch(e){toast(e.message==='weak_password'?'كلمة المرور ضعيفة':'تعذر تغيير كلمة المرور')}finally{b.disabled=false}}
boot().catch(e=>{console.error(e);location.href='./'});