import { createRemoteJWKSet, jwtVerify } from "npm:jose@5.9.6";

const ISSUER='https://token.actions.githubusercontent.com';
const AUDIENCE='digital-compass-public-runner';
const REPOSITORY='psycho-666/digital-compass-site';
const REF='refs/heads/main';
const WORKFLOW='psycho-666/digital-compass-site/.github/workflows/ops_worker.yml@refs/heads/main';
const JWKS=createRemoteJWKSet(new URL('https://token.actions.githubusercontent.com/.well-known/jwks'));
const PROJECT_URL=Deno.env.get('SUPABASE_URL')!;
const SECRET_KEYS=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');
const SECRET_KEY=SECRET_KEYS['default'];
const STICKY=new Set(['LOCAL_CONFIRMED','NOT_LOCAL']);

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex, nofollow, noarchive'}})}
function now(){return new Date().toISOString()}
function leaseUntil(minutes=55){return new Date(Date.now()+minutes*60*1000).toISOString()}
function today(){return new Date().toISOString().slice(0,10)}
function text(v:any,n=1200){return String(v??'').slice(0,n)}
function url(v:any){const s=String(v||'').trim();return /^https?:\/\//i.test(s)?s.slice(0,1800):null}
function num(v:any){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):null}
function bool(v:any){return v===true}
function obj(v:any,max=30000){if(!v||typeof v!=='object')return {};const s=JSON.stringify(v);if(s.length>max)throw new Error('object_too_large');return v}
function arr(v:any,max=40,itemMax=800){return Array.isArray(v)?v.slice(0,max).map(x=>typeof x==='string'?text(x,itemMax):x):[]}

async function auth(req:Request){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))throw new Error('missing_bearer');const {payload}=await jwtVerify(h.slice(7).trim(),JWKS,{issuer:ISSUER,audience:AUDIENCE,algorithms:['RS256']});if(payload.repository!==REPOSITORY||payload.ref!==REF||payload.workflow_ref!==WORKFLOW)throw new Error('identity_not_allowed');if(!['push','schedule','workflow_dispatch'].includes(String(payload.event_name||'')))throw new Error('event_not_allowed');return payload}
async function rest(path:string,init:RequestInit={}){if(!SECRET_KEY)throw new Error('service_key_unavailable');const h=new Headers(init.headers||{});h.set('apikey',SECRET_KEY);h.set('authorization',`Bearer ${SECRET_KEY}`);h.set('content-type','application/json');const r=await fetch(`${PROJECT_URL}/rest/v1/${path}`,{...init,headers:h});const t=await r.text();if(!r.ok)throw new Error(`rest_${r.status}_${t.slice(0,400)}`);return t?JSON.parse(t):null}
async function rpc(name:string,body:any={}){return await rest(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
async function patch(table:string,filter:string,body:any,prefer='return=minimal'){return await rest(`${table}?${filter}`,{method:'PATCH',headers:{Prefer:prefer},body:JSON.stringify(body)})}
async function insert(table:string,body:any,prefer='return=representation'){return await rest(table,{method:'POST',headers:{Prefer:prefer},body:JSON.stringify(body)})}
async function one(table:string,filter:string){const rows=await rest(`${table}?${filter}&limit=1`)||[];return rows[0]||null}

async function claimCommand(type:string){const rows=await rest(`automation_commands?status=eq.QUEUED&command_type=eq.${encodeURIComponent(type)}&select=id,attempt_count,max_attempts&order=requested_at.asc,id.asc&limit=1`)||[];if(!rows.length)return null;const row=rows[0],attempt=Number(row.attempt_count||0)+1;if(attempt>Number(row.max_attempts||3)){await patch('automation_commands',`id=eq.${row.id}&status=eq.QUEUED`,{status:'FAILED',completed_at:now(),error_message:'Maximum automatic attempts exceeded',lease_expires_at:null,last_heartbeat_at:now()});return null}const claimed=await patch('automation_commands',`id=eq.${row.id}&status=eq.QUEUED`,{status:'RUNNING',started_at:now(),error_message:null,attempt_count:attempt,lease_expires_at:leaseUntil(),last_heartbeat_at:now()},'return=representation')||[];return claimed.length?Number(row.id):null}
async function finishCommand(id:number,type:string,status:string,result:any,error:any=null){if(!id)return;const rows=await rest(`automation_commands?id=eq.${id}&command_type=eq.${encodeURIComponent(type)}&status=eq.RUNNING&select=id&limit=1`)||[];if(!rows.length)throw new Error('command_not_claimed');await patch('automation_commands',`id=eq.${id}`,{status,completed_at:now(),result:obj(result),error_message:error?text(error,4000):null,lease_expires_at:null,last_heartbeat_at:now()})}

async function candidateForProfile(profileId:number){const rows=await rest(`social_discovery_candidates?social_profile_id=eq.${profileId}&select=*&order=updated_at.desc&limit=1`)||[];return rows[0]||null}
async function adsFor(profileId:number,candidateId?:number){let q=`public_ad_observations?social_profile_id=eq.${profileId}&select=id,external_ad_id,advertiser_name,ad_url,creative_text,call_to_action,landing_url,is_active,observed_at,public_metadata,discovery_candidate_id&order=observed_at.desc&limit=30`;let rows=await rest(q)||[];if(!rows.length&&candidateId)rows=await rest(`public_ad_observations?discovery_candidate_id=eq.${candidateId}&select=id,external_ad_id,advertiser_name,ad_url,creative_text,call_to_action,landing_url,is_active,observed_at,public_metadata,discovery_candidate_id&order=observed_at.desc&limit=30`)||[];return rows}

async function claimEnrichment(){
  const commandId=await claimCommand('SOCIAL_ENRICHMENT');
  if(!commandId) return {ok:true,action:'claim_social_enrichment',tasks:[],command_id:null,preserved:0};
  try{await rpc('refresh_social_enrichment_queue',{p_limit:20})}catch(_e){}
  const reqs=await rpc('claim_social_research_requests',{p_limit:10})||[];const tasks=[];let preserved=0;
  for(const req of reqs){const profile=await one('social_profiles',`id=eq.${req.target_social_profile_id}&select=*`);if(!profile){await patch('social_research_requests',`id=eq.${req.id}`,{status:'PARTIAL',completed_at:now(),error_message:'social profile not found'});continue}const cand=await candidateForProfile(Number(profile.id));const company=profile.company_id?await one('companies',`id=eq.${profile.company_id}&select=*`):null;if(!cand){await patch('social_research_requests',`id=eq.${req.id}`,{status:'PARTIAL',completed_at:now(),error_message:'discovery candidate not found'});continue}if(STICKY.has(String(cand.market_relevance_status||''))){preserved++;await patch('social_research_requests',`id=eq.${req.id}`,{status:'SUCCEEDED',completed_at:now(),error_message:null,result:{classification:cand.market_relevance_status,preserved_confirmed_classification:true,business_country:cand.business_country_hint,evidence:cand.local_relevance_evidence||{}}});continue}const ads=await adsFor(Number(profile.id),Number(cand.id));tasks.push({request:req,profile,candidate:cand,company,ads})}
  if(commandId&&tasks.length===0)await finishCommand(commandId,'SOCIAL_ENRICHMENT','SUCCEEDED',{processed:preserved,note:'No unresolved enrichment tasks pending.'});
  return {ok:true,action:'claim_social_enrichment',tasks,command_id:tasks.length?commandId:null,preserved};
}

async function completeEnrichment(body:any){
  const id=Number(body.request_id);const req=await one('social_research_requests',`id=eq.${id}&status=eq.RUNNING&select=*`);if(!req)throw new Error('research_not_claimed');const profile=await one('social_profiles',`id=eq.${req.target_social_profile_id}&select=*`);if(!profile)throw new Error('profile_missing');const cand=await candidateForProfile(Number(profile.id));if(!cand)throw new Error('candidate_missing');if(STICKY.has(String(cand.market_relevance_status||''))){await patch('social_research_requests',`id=eq.${id}`,{status:'SUCCEEDED',completed_at:now(),error_message:null,result:{classification:cand.market_relevance_status,preserved_confirmed_classification:true}});return {ok:true,status:'SUCCEEDED',classification:cand.market_relevance_status}}
  const score=Math.max(0,Math.min(100,Number(body.local_signal_score||0)));const identity=body.identity_resolved===true;const classification=score>=60?'LOCAL_CONFIRMED':String(cand.market_relevance_status||'TARGETING_IRAQ');const cities=arr(body.cities,5,120).map(String);const phone=text(body.phone,80)||cand.phone||null;const wa=url(body.whatsapp)||cand.whatsapp||null;const landing=url(body.landing_url)||cand.landing_url||null;const email=text(body.email,240)||cand.email||null;const evidence=obj(body.evidence||{});
  const candPatch:any={local_relevance_evidence:evidence,landing_url:landing,phone,whatsapp:wa,email,city_hint:cities[0]||cand.city_hint||null,updated_at:now()};if(classification==='LOCAL_CONFIRMED'){candPatch.market_relevance_status='LOCAL_CONFIRMED';candPatch.business_country_hint='Iraq'}await patch('social_discovery_candidates',`id=eq.${cand.id}`,candPatch);
  await patch('social_profiles',`id=eq.${profile.id}`,{website_url:landing||profile.website_url||null,contact_phone:phone||profile.contact_phone||null,contact_email:email||profile.contact_email||null,whatsapp_url:wa||profile.whatsapp_url||null,source_checked_at:now(),updated_at:now()});
  if(profile.company_id&&classification==='LOCAL_CONFIRMED'){const company=await one('companies',`id=eq.${profile.company_id}&select=*`);if(company)await patch('companies',`id=eq.${company.id}`,{country:'Iraq',city:cities[0]||company.city||null,phone:phone||company.phone||null,general_email:email||company.general_email||null,contactable:Boolean(phone||email||wa||landing),updated_at:now()})}
  const succeeded=classification==='LOCAL_CONFIRMED';const result={classification,local_signal_score:score,direct_ad_signal_score:Number(body.direct_ad_signal_score||0),identity_resolved:identity,sales_readiness:identity?'READY_FOR_AUDIT':'IDENTITY_REQUIRED',city:cities[0]||null,landing_url:landing,phone,matched_sources:arr(body.matched_sources,6,1800),worker:'OIDC_PUBLIC_SOCIAL_ENRICHMENT_V1'};await patch('social_research_requests',`id=eq.${id}`,{status:succeeded?'SUCCEEDED':'PARTIAL',completed_at:now(),result,error_message:succeeded?null:'Public evidence, including active-ad signals, is still insufficient to confirm Iraq-local relevance.'});return {ok:true,status:succeeded?'SUCCEEDED':'PARTIAL',...result}
}

async function claimAudit(){
  const commandId=await claimCommand('SOCIAL_AUDIT');
  if(!commandId) return {ok:true,action:'claim_social_audit',tasks:[],command_id:null,run_id:null};const first=await rest(`social_audits?status=eq.PENDING&platform=eq.FACEBOOK&select=id,company_id,social_profile_id,platform,audit_date&order=created_at.asc,id.asc&limit=15`)||[];let candidates=[...first];if(candidates.length<15){const other=await rest(`social_audits?status=eq.PENDING&platform=neq.FACEBOOK&select=id,company_id,social_profile_id,platform,audit_date&order=created_at.asc,id.asc&limit=${15-candidates.length}`)||[];candidates.push(...other)}const tasks=[];
  for(const row of candidates){const claimed=await patch('social_audits',`id=eq.${row.id}&status=eq.PENDING`,{status:'RUNNING',error_message:null,updated_at:now()},'return=representation')||[];if(!claimed.length)continue;const profile=await one('social_profiles',`id=eq.${row.social_profile_id}&select=*`);const company=await one('companies',`id=eq.${row.company_id}&select=*`);if(!profile||!company){await patch('social_audits',`id=eq.${row.id}`,{status:'NEEDS_REVIEW',error_message:'Missing company/profile',audited_at:now(),updated_at:now()});continue}const cand=await candidateForProfile(Number(profile.id));const ads=await adsFor(Number(profile.id),cand?Number(cand.id):undefined);tasks.push({audit:row,profile,company,candidate:cand,ads})}
  let runId=null;if(tasks.length){const rows=await insert('social_research_runs',{run_date:today(),country:'Iraq',run_type:'PROFILE_AUDIT',source:'OIDC_PUBLIC_PROFILE_BROWSER_V1',status:'RUNNING',started_at:now()})||[];runId=rows[0]?.id||null}
  if(commandId&&tasks.length===0)await finishCommand(commandId,'SOCIAL_AUDIT','SUCCEEDED',{processed:0,note:'No pending social audits.'});return {ok:true,action:'claim_social_audit',tasks,command_id:tasks.length?commandId:null,run_id:runId}
}

function sanitizeScore(v:any){return v===null||v===undefined?null:num(v)}
async function completeAudit(body:any){
  const id=Number(body.audit_id);const audit=await one('social_audits',`id=eq.${id}&status=eq.RUNNING&select=*`);if(!audit)throw new Error('audit_not_claimed');const profile=await one('social_profiles',`id=eq.${audit.social_profile_id}&select=*`);const company=await one('companies',`id=eq.${audit.company_id}&select=*`);if(!profile||!company)throw new Error('profile_or_company_missing');const cand=await candidateForProfile(Number(profile.id));
  const p=body.profile_update||{};await patch('social_profiles',`id=eq.${profile.id}`,{display_name:text(p.display_name,300)||profile.display_name||null,bio_text:text(p.bio_text,1200)||profile.bio_text||null,contact_email:text(p.contact_email,240)||profile.contact_email||null,contact_phone:text(p.contact_phone,80)||profile.contact_phone||null,whatsapp_url:url(p.whatsapp_url)||profile.whatsapp_url||null,website_url:url(p.website_url)||profile.website_url||null,public_activity_status:text(p.public_activity_status,80)||profile.public_activity_status||'UNKNOWN',source_checked_at:now(),raw_public_snapshot:obj(p.raw_public_snapshot||{}),updated_at:now()});
  if(cand){const c=body.candidate_update||{};await patch('social_discovery_candidates',`id=eq.${cand.id}`,{advertiser_name:text(c.advertiser_name,300)||cand.advertiser_name||null,page_name:text(c.page_name,300)||cand.page_name||null,email:text(c.email,240)||cand.email||null,phone:text(c.phone,80)||cand.phone||null,whatsapp:url(c.whatsapp)||cand.whatsapp||null,landing_url:url(c.landing_url)||cand.landing_url||null,updated_at:now()})}
  if(body.company_update&&typeof body.company_update==='object'){const c=body.company_update;const patchBody:any={};if(c.name&&(!company.name||company.name==='Social Advertiser'||String(company.name).startsWith('http')))patchBody.name=text(c.name,300);if(c.phone)patchBody.phone=text(c.phone,80);if(c.general_email)patchBody.general_email=text(c.general_email,240);if(Object.keys(patchBody).length){patchBody.updated_at=now();await patch('companies',`id=eq.${company.id}`,patchBody)}}
  const a=body.audit_update||{};const core=[sanitizeScore(a.profile_completeness_score),sanitizeScore(a.posting_consistency_score),sanitizeScore(a.content_quality_score),sanitizeScore(a.engagement_health_score),sanitizeScore(a.conversion_path_score),sanitizeScore(a.response_readiness_score)];const requested=core.every(v=>v!==null)?'COMPLETED':'NEEDS_REVIEW';const auditPatch:any={profile_completeness_score:core[0],posting_consistency_score:core[1],content_quality_score:core[2],brand_consistency_score:sanitizeScore(a.brand_consistency_score),engagement_health_score:core[3],conversion_path_score:core[4],local_relevance_score:sanitizeScore(a.local_relevance_score),advertising_signal_score:sanitizeScore(a.advertising_signal_score),response_readiness_score:core[5],status:requested,detected_language:text(a.detected_language,10)||null,posts_observed_30d:Number.isInteger(Number(a.posts_observed_30d))?Number(a.posts_observed_30d):null,has_clear_cta:bool(a.has_clear_cta),has_whatsapp_cta:bool(a.has_whatsapp_cta),has_booking_or_order_path:bool(a.has_booking_or_order_path),has_recent_activity:a.has_recent_activity===true?true:a.has_recent_activity===false?false:null,has_public_ad_activity:bool(a.has_public_ad_activity),findings:arr(a.findings,30,500),strengths:arr(a.strengths,20,500),gaps:arr(a.gaps,20,500),recommended_actions:arr(a.recommended_actions,20,500),evidence:obj(a.evidence||{}),audited_at:now(),updated_at:now(),error_message:null};await patch('social_audits',`id=eq.${id}`,auditPatch);
  const saved=await one('social_audits',`id=eq.${id}&select=id,status,overall_social_health_score,management_need_score,error_message`);return {ok:true,audit_id:id,status:saved?.status,overall_social_health_score:saved?.overall_social_health_score,management_need_score:saved?.management_need_score,error_message:saved?.error_message}
}

async function finishBatch(body:any){const type=String(body.command_type||'');if(!['SOCIAL_AUDIT','SOCIAL_ENRICHMENT'].includes(type))throw new Error('bad_type');const processed=Math.max(0,Number(body.processed||0)),failures=Math.max(0,Number(body.failures||0)),review=Math.max(0,Number(body.needs_review||0)),completed=Math.max(0,Number(body.completed||0));let opportunities:any=null;if(type==='SOCIAL_AUDIT'){opportunities=await rpc('refresh_social_management_opportunities',{p_date:today()});const runId=Number(body.run_id);if(runId)await patch('social_research_runs',`id=eq.${runId}`,{status:failures?'PARTIAL':'SUCCEEDED',audits_completed:completed,opportunities_created:Array.isArray(opportunities)&&opportunities[0]?Number(opportunities[0].total_qualified||0):0,completed_at:now(),notes:JSON.stringify({processed,completed,needs_review:review,failed:failures,worker:'OIDC_PUBLIC_PROFILE_BROWSER_V1'})})}const commandId=Number(body.command_id);if(commandId)await finishCommand(commandId,type,failures?'FAILED':'SUCCEEDED',{processed,failures,completed,needs_review:review,worker:type==='SOCIAL_AUDIT'?'OIDC_PUBLIC_PROFILE_BROWSER_V1':'OIDC_PUBLIC_SOCIAL_ENRICHMENT_V1'},failures?'One or more public social worker tasks failed.':null);return {ok:true,type,processed,failures,completed,needs_review:review,opportunities}
}

Deno.serve(async(req:Request)=>{if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const identity=await auth(req);const body=await req.json().catch(()=>({}));const action=String(body.action||'');if(action==='probe')return json({ok:true,repository:identity.repository,run_id:identity.run_id});if(action==='claim_social_enrichment')return json(await claimEnrichment());if(action==='complete_social_enrichment')return json(await completeEnrichment(body));if(action==='claim_social_audit')return json(await claimAudit());if(action==='complete_social_audit')return json(await completeAudit(body));if(action==='finish_social_batch')return json(await finishBatch(body));return json({error:'action_not_supported'},400)}catch(e){console.error('github-social-worker-bridge failed',e);return json({error:'unauthorized_or_invalid'},401)}});
