import * as cheerio from 'cheerio';

const BRIDGE='https://xnoalyxxrjyovivdeojo.supabase.co/functions/v1/github-core-worker-bridge';
const TOKEN=process.env.OIDC_TOKEN;
const UA='DigitalCompassAudit/1.0';
const CTA=['contact us','get a quote','request a quote','book now','call now','whatsapp','تواصل معنا','اتصل بنا','احجز','اطلب الآن','واتساب','احصل على عرض'];
const BOOKING=['book','booking','appointment','reserve','reservation','schedule','حجز','احجز','موعد'];
const PROOF=['testimonial','reviews','our clients','partners','trusted by','case study','آراء العملاء','تقييمات','عملاؤنا','شركاؤنا','قصص نجاح'];

async function bridge(body){const r=await fetch(BRIDGE,{method:'POST',headers:{authorization:`Bearer ${TOKEN}`,'content-type':'application/json'},body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw new Error(`bridge_${r.status}_${t.slice(0,500)}`);return JSON.parse(t)}
const now=()=>new Date().toISOString();
const socialCount=c=>['instagram_url','facebook_url','linkedin_url'].filter(k=>c[k]).length;
function normalize(raw){if(!raw)return null;try{return new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`).href}catch{return null}}
function candidates(raw){const original=normalize(raw);if(!original)return[];const u=new URL(original),hosts=[u.hostname];if(u.hostname.startsWith('www.'))hosts.push(u.hostname.slice(4));else hosts.push(`www.${u.hostname}`);const schemes=u.protocol==='https:'?['https:','http:']:['http:','https:'];const paths=[u.pathname||'/'];if(paths[0]!=='/')paths.push('/');return [...new Set(schemes.flatMap(protocol=>hosts.flatMap(hostname=>paths.map(pathname=>new URL(pathname,`${protocol}//${hostname}`).href))))].slice(0,8)}
async function allowed(url){try{const u=new URL(url),r=await fetch(`${u.protocol}//${u.host}/robots.txt`,{headers:{'user-agent':UA},signal:AbortSignal.timeout(7000)});if(!r.ok)return true;const lines=(await r.text()).split(/\r?\n/);let applies=false;for(const raw of lines){const line=raw.split('#')[0].trim();if(/^user-agent\s*:/i.test(line))applies=/\*|digitalcompassaudit/i.test(line);else if(applies&&/^disallow\s*:\s*\/$/i.test(line))return false}return true}catch{return true}}
function noWebsite(company){const channels=socialCount(company),contacts=['general_email','phone','whatsapp'].filter(k=>company[k]).length,t=now();return{company_id:company.id,audit_type:'NO_WEBSITE',status:'COMPLETED',social_channels_count:channels,audit_score:Math.min(100,70+channels*5+Math.min(contacts,2)*5),findings:{summary:'No dedicated business website detected.',public_social_channels:channels,contact_methods_detected:contacts,recommended_validation:['Confirm social account is active','Confirm business details from public sources','Decide PREVIEW vs PROTOTYPE after social review']},started_at:t,finished_at:t}}
function unavailable(company,attempts,started){const statuses=attempts.map(x=>x.http_status).filter(Boolean),errors=attempts.map(x=>x.error).filter(Boolean),blocked=statuses.some(x=>[401,403,429].includes(x)),stale=statuses.some(x=>[404,410].includes(x)),robots=attempts.length&&attempts.every(x=>x.outcome==='ROBOTS_BLOCK');const status=robots?'BLOCKED_BY_ROBOTS':blocked?'BLOCKED_BY_SITE':stale?'STALE_URL':'UNREACHABLE';return{company_id:company.id,audit_type:'WEBSITE',audited_url:normalize(company.website_url),status,http_status:statuses.find(x=>[401,403,404,410,429].includes(x))||null,social_channels_count:socialCount(company),audit_score:null,findings:{summary:`Website audit unavailable: ${status}.`,availability_classification:status,attempts,score_withheld:true,recommended_validation:'Verify the public destination before outreach.'},started_at:started,finished_at:now(),error_message:(errors.slice(0,3).join('; ')||status).slice(0,1000)}}
async function website(company){const started=now(),attempts=[];for(const url of candidates(company.website_url)){if(!(await allowed(url))){attempts.push({url,outcome:'ROBOTS_BLOCK',http_status:null});continue}try{const r=await fetch(url,{redirect:'follow',headers:{'user-agent':UA,accept:'text/html,application/xhtml+xml','accept-language':'en,ar;q=0.9'},signal:AbortSignal.timeout(15000)}),ctype=(r.headers.get('content-type')||'').toLowerCase();attempts.push({url,final_url:r.url,http_status:r.status,content_type:ctype.slice(0,120)});if(r.status>=400||(!ctype.includes('text/html')&&!ctype.includes('application/xhtml+xml')))continue;const html=(await r.text()).slice(0,2000000),$=cheerio.load(html),links=$('a[href]').map((_,e)=>$(e).attr('href')).get(),text=(`${$('body').text()} ${links.join(' ')}`).toLowerCase(),linkText=links.join(' ').toLowerCase();const has={whatsapp:/wa\.me|api\.whatsapp\.com|whatsapp:\/\//.test(linkText),phone:linkText.includes('tel:'),email:linkText.includes('mailto:'),booking:BOOKING.some(x=>text.includes(x)),cta:CTA.some(x=>text.includes(x)),proof:PROOF.some(x=>text.includes(x)),form:$('form').length>0,viewport:$('meta[name="viewport"]').length>0,ssl:new URL(r.url).protocol==='https:',description:$('meta[name="description"]').attr('content')?.trim()||null};const missing=[];if(!has.cta)missing.push('clear_call_to_action');if(!has.form)missing.push('contact_or_lead_form');if(!has.whatsapp)missing.push('whatsapp_link');if(!has.phone&&!has.email)missing.push('direct_phone_or_email_link');if(!has.viewport)missing.push('mobile_viewport');if(!has.proof)missing.push('social_proof');if(!has.description)missing.push('meta_description');if(!has.ssl)missing.push('https');const score=Math.min(100,(!has.cta?20:0)+(!has.form?15:0)+(!has.whatsapp?10:0)+(!has.phone&&!has.email?10:0)+(!has.viewport?15:0)+(!has.proof?10:0)+(!has.description?5:0)+(!has.ssl?15:0));return{company_id:company.id,audit_type:'WEBSITE',audited_url:r.url,status:'COMPLETED',http_status:r.status,page_title:($('title').text().trim()||'').slice(0,500)||null,meta_description:has.description?.slice(0,1000)||null,has_ssl:has.ssl,has_mobile_viewport:has.viewport,has_clear_cta:has.cta,has_contact_form:has.form,has_whatsapp:has.whatsapp,has_phone_link:has.phone,has_email_link:has.email,has_booking:has.booking,has_social_proof:has.proof,social_channels_count:socialCount(company),audit_score:score,findings:{final_url:r.url,missing_signals:missing,note:'Homepage-only heuristic; review context before making sales claims.',availability_fallbacks:attempts,original_listed_url:normalize(company.website_url)},started_at:started,finished_at:now(),error_message:null}}catch(e){attempts.push({url,http_status:null,error:String(e).slice(0,500)})}}return unavailable(company,attempts,started)}

async function main(){const claim=await bridge({action:'claim_deep_audit'}),id=claim.command_id,tasks=claim.tasks||[];if(!id||!tasks.length){console.log('No deep-audit command queued.');return}let completed=0,failures=0;try{for(const task of tasks){let audit;try{audit=task.shortlist.opportunity_track==='NO_WEBSITE'?noWebsite(task.company):await website(task.company);await bridge({action:'complete_deep_audit',command_id:id,audit});if(audit.status==='COMPLETED')completed++;else failures++}catch(e){failures++;console.error(`Audit failed for company ${task.company?.id}:`,e)}}await bridge({action:'finish_deep_audit',command_id:id,status:'SUCCEEDED',processed:tasks.length,completed,non_completed:tasks.length-completed,failures});console.log(`Deep audit finished: processed=${tasks.length} completed=${completed} non_completed=${tasks.length-completed}`)}catch(e){await bridge({action:'finish_deep_audit',command_id:id,status:'FAILED',processed:tasks.length,completed,non_completed:tasks.length-completed,failures:failures+1,error_message:String(e).slice(0,4000)});throw e}}

await main();
